# Generated by Django 5.2.1 on 2025-06-03 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('advcourses', '0003_advcourse_price'),
        ('bootcamps', '0006_bootcamp_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unpaid', 'پرداخت نشده'), ('pending_review', 'در انتظار بررسی'), ('paid', 'پرداخت شده')], default='unpaid', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_advcourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='advcourses.advcourse')),
                ('related_bootcamp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bootcamps.bootcamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('offline', 'Offline'), ('online', 'Online')], max_length=10)),
                ('tracking_code', models.CharField(blank=True, max_length=50)),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/')),
                ('note', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('billing_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payments.billingrecord')),
            ],
        ),
    ]
