# Generated by Django 5.2.1 on 2025-06-03 11:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advcourses', '0003_advcourse_price'),
        ('bootcamps', '0006_bootcamp_price'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BillingRecord',
            new_name='Invoice',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='billing_record',
            new_name='invoice',
        ),
    ]
