# Generated by Django 4.2 on 2025-05-18 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otpcode',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
