# Generated by Django 5.2.1 on 2025-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('registration_open', 'در حال ثبت\u200cنام'), ('in_progress', 'در حال برگزاری'), ('completed', 'برگزار شده'), ('canceled', 'لغو شده')], default='draft', max_length=20)),
                ('platform_name', models.CharField(max_length=100)),
                ('is_live', models.BooleanField(default=False)),
                ('access_instructions', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
