# Generated by Django 5.2.1 on 2025-06-02 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advcourses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvCourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('mentor', 'منتور'), ('teacher', 'استاد')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'بررسی نشده'), ('reviewing', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'تایید نشده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('advcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='advcourses.advcourse')),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdvCourseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('mentor', 'منتور'), ('teacher', 'استاد')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('advcourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='advcourses.advcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-joined_at'],
                'abstract': False,
                'unique_together': {('advcourse', 'user')},
            },
        ),
    ]
