# Generated by Django 5.2.1 on 2025-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advcourses', '0002_advcourseregistration_advcourseuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='advcourse',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
