# Generated by Django 4.2 on 2025-05-25 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bootcamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('registration_open', 'در حال ثبت\u200cنام'), ('in_progress', 'در حال برگزاری'), ('completed', 'برگزار شده'), ('canceled', 'لغو شده')], default='draft', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BootCampRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=20)),
                ('national_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('mentor', 'منتور'), ('teacher', 'استاد')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'بررسی نشده'), ('reviewing', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'تایید نشده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='bootcamps.bootcamp')),
            ],
        ),
        migrations.CreateModel(
            name='BootcampUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('mentor', 'منتور'), ('teacher', 'استاد')], max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='bootcamps.bootcamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('bootcamp', 'user')},
            },
        ),
    ]
