# Generated by Django 5.2.1 on 2025-05-31 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BootcampRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('role', models.CharField(choices=[('student', 'دانشجو'), ('mentor', 'منتور'), ('teacher', 'استاد')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'بررسی نشده'), ('reviewing', 'در حال بررسی'), ('approved', 'تایید شده'), ('rejected', 'تایید نشده')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bootcamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_requests', to='bootcamps.bootcamp')),
            ],
        ),
        migrations.DeleteModel(
            name='BootcampRegistrationRequest',
        ),
    ]
