# Generated by Django 5.2.1 on 2025-06-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0003_bootcampregistration_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
