# Generated by Django 5.2.1 on 2025-06-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0004_bootcamp_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bootcampregistration',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='bootcampregistration',
            name='user',
        ),
    ]
