# Generated by Django 5.2.1 on 2025-06-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bootcamps', '0005_alter_bootcampregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bootcamp',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
